package main

import "html/template"

type ServiceTemplateInput struct {
	PluginVersion      string
	ProtocVersion      string
	FileDescriptorPath string
	PackageName        string
	Events             []Event
}

var ServiceTemplate = template.Must(
	template.New("service").Parse(`// Code generated by protoc-gen-go-service. DO NOT EDIT.
// versions:
//     - protoc-gen-go-event {{ .PluginVersion }}
//     - protoc              {{ .ProtocVersion }}
// source: {{ .FileDescriptorPath }}

package {{ .PackageName }}

const (
	{{ range .Events }}
	{{ .TopicKey }} = "{{ .TopicValue }}"
	{{ .SQLTopicKey }} = "{{ .SQLTopicValue }}"{{ end }}
)
`),
)
