name: "lint"

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  golangci-lint:
    uses: weave-labs/ci/.github/workflows/golangci-lint.yaml@main
    secrets:
      APP_ID: ${{ secrets.STITCH_ID }}
      APP_PRIVATE_KEY: ${{ secrets.STITCH_PRIVATE_KEY }}